//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlassStorage
    {
        public int Id { get; set; }
        public string BarCode { get; set; }
        public string Station { get; set; }
    }
}
